allowBuilds:
  unrs-resolver: true
minimumReleaseAgeExclude:
  - '@expo/cli@57.0.22'
  - '@expo/env@2.4.3'
  - '@expo/fingerprint@0.20.12'
  - '@expo/metro-config@57.0.12'
  - expo-constants@57.0.17
  - expo-font@57.0.3
  - expo@57.0.20
